# Python & NumPy Туториал

Оригинальный ноутбук взят и переведён из курса [CS 231n](http://cs231n.stanford.edu/syllabus.html).

Так же существует курс на Stepik по основам Python и Numpy для математики: https://stepik.org/course/3356/

Python 3 и NumPy будут широко использоваться на протяжении всего курса, поэтому важно быть знакомым с ними.  

Большое количество материала для этого ноутбука было взято из туториала Justin Johnson [Python & NumPy](http://cs231n.github.io/python-numpy-tutorial/). В данный момент не все из этого туториала находится в этом ноутбуке, и не все из этого ноутбука находится в туториале.

## Python 3

Если вы не знакомы с Python 3, Вот некоторые из наиболее распространенных изменений от Python 2, на которые стоит обратить внимание. Хотя Python 2 уже оффициально мёртв, не все об этом могут знать.

### Print - это функция

In [1]:
print("Hello!")

Hello!


Без скобок работать не будет.

In [2]:
print "Hello!"

SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Hello!")? (<ipython-input-2-9d266092e9bc>, line 1)

### Деление чисел с плавающей запятой поддерживается по-умолчанию

In [7]:
5 / 2

2.5

Для целочисленного деления используйте два обратных слеша:

In [8]:
5 // 2

2

### Нет xrange

xrange из Python 2 был переименован в "range" для Python 3. В Python 3, range(3) не создаёт список из трёх элементов. Вместо этого создаётся эффективный по памяти итератор.

In [9]:
for i in range(3):
    print(i)

0
1
2


In [10]:
range(3)

range(0, 3)

In [11]:
# Если необходимо получить список из итератора, то оборачиваем его в list():
print(list(range(3)))

[0, 1, 2]


# NumPy

"NumPy является фундаментальной библиотекой для научных вычислений в Python. Эта библиотека предоставляет многомерный объект array, множество производных объектов(таких как массивы-маски и матрицы), а также набор процедур для быстрых операций с массивами, включая математические, логические, манипуляции с формой, сортировку, селекция, операции ввода-вывода, дискретные преобразования Фурье, базовую линейную алгебру, базовые статистические операции, случайное моделирование и многое другое."
- https://docs.scipy.org/doc/numpy-1.10.1/user/whatisnumpy.html.

In [12]:
import numpy as np

Давайте рассмотрим пример, показывающий, насколько мощным является NumPy. Предположим, что у нас есть два списка a и b, состоящие из первых 100,000 неотрицательных чисел, и мы хотим создать новый список c, в котором *i*-тый элемент - это a[i] + 2 * b[i].  

Без NumPy:

In [13]:
%%time
a = list(range(100000))
b = list(range(100000))

Wall time: 2.99 ms


In [14]:
%%time
for _ in range(10):
    c = []
    for i in range(len(a)):
        c.append(a[i] + 2 * b[i])

Wall time: 395 ms


С NumPy:

In [15]:
%%time
a = np.arange(100000)
b = np.arange(100000)

Wall time: 2.99 ms


In [16]:
%%time
for _ in range(10):
    c = a + 2 * b

Wall time: 4.99 ms


Результат в 20-50 раз (и даже больше) быстрее, и мы смогли сделать это в меньшем количестве строк кода (сам код стал более интуитивно понятен)!

Обычный Python работает намного медленнее из-за проверки типов и других накладных расходов, связанных с необходимостью интерпретировать код и поддерживать абстракции Python.

Например, если мы делаем некоторое добавление в цикле, то постоянная проверка типа в цикле приведет к гораздо большему количеству инструкций, чем просто выполнение обычной операции добавления. NumPy, используя оптимизированный предварительно скомпилированный код C, способен избежать многих накладных расходов.

Процесс, который мы использовали выше, является **векторизация**. Векторизация относится к применению операций к массивам, а не только к отдельным элементам (т.е. без циклов).

Почему векторизация?
1. Намного быстрее
2. Легче читать и меньше строк кода
3. Ближе к математическим обозначениям

Векторизация - одна из главных причин, почему NumPy так мощен.

## ndarray

ndarrays, n-мерные массивы однородных типов данных, являются основными типами данных, используемыми в NumPy. Поскольку эти массивы имеют один и тот же тип и фиксированный размер при создании, они предлагают меньшую гибкость, чем списки Python, но могут быть существенно более эффективными во время выполнения и с точки зрения памяти. Списки Python - это массивы указателей на объекты, добавляющие слой абстракции.

Число измерений - это ранг массива; форма массива - это кортеж целых чисел, определяющих размер массива вдоль каждого измерения.

In [17]:
# Инициализация ndarrays с помощью списков Python, например:
a = np.array([1, 2, 3])          # Создаёт одномерный массив
print('type:', type(a))          # "<class 'numpy.ndarray'>"
print('shape:', a.shape)         # "(3,)"
print('a:', a)                   # "[1 2 3]"

a_cpy = a.copy()
a[0] = 5                         # Меняет элемент массива
print('a modeified:', a)         # "[5 2 3]"
print('a copy:', a_cpy)

b = np.array([[1, 2, 3],
              [4, 5, 6]])        # Создаёт двумерный массив (матрицу)
print('shape:', b.shape)         # "(2, 3)"
print(b[0, 0], b[0, 1], b[1, 0]) # "1 2 4"

type: <class 'numpy.ndarray'>
shape: (3,)
a: [1 2 3]
a modeified: [5 2 3]
a copy: [1 2 3]
shape: (2, 3)
1 2 4


Так же существует множество других способов создать массив:

In [18]:
a = np.zeros((2, 2))   # Создаёт массив нулей
print(a)               #  "[[ 0.  0.]
                       #    [ 0.  0.]]"

b = np.full((2, 2), 7)  # Создаёт массив константных значений
print(b)                # "[[ 7.  7.]
                        #   [ 7.  7.]]"

c = np.eye(2, dtype=np.int8)  # Создаёт единичную матрицу 2 x 2, заполненную целочисленныи значениями
print(c)                      # "[[ 1.  0.]
                              #   [ 0.  1.]]"

d = np.random.random((2, 2))  # Создаёт массив случайных значений
print(d)                      # Возможный вывод "[[ 0.91940167  0.08143941]
                              #                   [ 0.68744134  0.87236687]]"

[[0. 0.]
 [0. 0.]]
[[7 7]
 [7 7]]
[[1 0]
 [0 1]]
[[0.69831371 0.3583393 ]
 [0.30082321 0.44891397]]


В NumPy можно при создании массива можно выбирать тип данных. Причём типы могут быть указаны через Python типы, такие как int, float; в виде строчек 

Как создать матрицу 2 на 2 из единиц?

In [19]:
a = np.ones((2, 2), dtype='uint32')  # Создаёт матрицу целочисленных положительных единиц
print(a)                             # "[[ 1  1]
                                     #   [ 1  1]]"

[[1 1]
 [1 1]]


Важно отслеживать форму; знание размеров будет очень полезно для отладки, при вычислении градиентов и других причин.

In [20]:
nums = np.arange(8)
print(nums)
print(nums.shape)

nums = nums.reshape((2, 4))
print('Reshaped:\n', nums)
print(nums.shape)

# -1 в reshape соответствует неизвестной размерности для которой numpy догадается,
# основываясь на других размерностях, и подставит нужно число.
# Можно указать только одну неизвестную размерность.
# Например, иногда у нас может быть неизвестное число точек данных, и
# тогда мы используем -1 вместо того, чтобы беспокоиться о реальном размере.
nums = nums.reshape((4, -1))
print('Reshaped with -1:\n', nums, '\nshape:\n', nums.shape)

# Вы также можете "выпрямить" массив в вектор с помощью .reshape(-1)
print('Flatten:\n', nums.reshape(-1), '\nshape:\n', nums.reshape(-1).shape)

[0 1 2 3 4 5 6 7]
(8,)
Reshaped:
 [[0 1 2 3]
 [4 5 6 7]]
(2, 4)
Reshaped with -1:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]] 
shape:
 (4, 2)
Flatten:
 [0 1 2 3 4 5 6 7] 
shape:
 (8,)


NumPy поддерживает объектно-ориентированную парадигму, такую, что ndarray имеет ряд методов и атрибутов с функциями, аналогичными тем, которые находятся во внешнем пространстве имен NumPy. Например, мы можем делать и то и другое:

In [21]:
nums = np.arange(8)
print(nums.min())     # 0
print(np.min(nums))   # 0
print(np.reshape(nums, (2, 4)))

0
0
[[0 1 2 3]
 [4 5 6 7]]


## Операции над массивами/Математика

NumPy поддерживает поэлементные операции, в результате которых создаётся новый массив:

In [22]:
x = np.array([[1, 2],
              [3, 4]], dtype=np.float64)
y = np.array([[5, 6],
              [7, 8]], dtype=np.float64)

# Поэлементная сумма
# [[ 6.0  8.0]
#  [10.0 12.0]]
print(np.array_equal(x + y, np.add(x, y)))

# Поэлементная разность
# [[-4.0 -4.0]
#  [-4.0 -4.0]]
print(np.array_equal(x - y, np.subtract(x, y)))

# Поэлементное умножение
# [[ 5.0 12.0]
#  [21.0 32.0]]
print(np.array_equal(x * y, np.multiply(x, y)))

# Поэлементное извлечение квадратного корня.
# [[ 1.          1.41421356]
#  [ 1.73205081  2.        ]]
print(np.array_equal(x ** (0.5), np.sqrt(x)))

# Можно даже возводить элементы одного массива в степень соответствующих
# элементов из другого массива.
print(y ** x) 

True
True
True
True
[[   5.   36.]
 [ 343. 4096.]]


How do we elementwise divide between two arrays?

In [23]:
x = np.array([[1, 2], [3, 4]], dtype=np.int64)
y = np.array([[5, 6], [7, 8]], dtype=np.int32)

# Поэлементное деление
# [[ 0.2         0.33333333]
#  [ 0.42857143  0.5       ]]
print(x / y)
print(np.divide(x, y))
print((x / y).dtype)  # тип данных float64
print((x // y).dtype) # тип данных int64, так как деление целочисленное и 
print(x // y)         # оба аргумента имеют целочисленный тип данных (при этом берётся тип с большим количеством бит)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
float64
int64
[[0 0]
 [0 0]]


Обратите внимание, что * поэлементное умножение, а не матричное. Для того, чтобы посчитать скалярное произведение векторов, умножение вектора на матрицу или матричное умножение, используется функция np.dot. dot может быть вызвана и как атрибут объекта array и как функция модуля numpy. Также вместо функции dot может быть использован оператор @.
Матричное умножение не коммутативно: $x \cdot y \neq y \cdot x$!

In [24]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# IСкалярное произведение векторов; все вернут 219
print(v.dot(w))
print(np.dot(v, w) == v @ w)

# Произведение матрицы на вектор; все вернут одномерный массив (вектор) [29 67]
print(x.dot(v))
print(np.array_equal(np.dot(x, v), x @ v))

# Матричное произведение; все вернут двумерный массив (матрицу)
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.array_equal(np.dot(x, y), x @ y))

219
True
[29 67]
True
[[19 22]
 [43 50]]
True


Есть много полезных функций, встроенных в NumPy, и часто мы можем выразить их через определенные оси (axes) ndarray:

In [25]:
x = np.array([[1, 2, 3], 
              [4, 5, 6]])

print(np.sum(x))          # Сумма всех элементов; prints "21"
print(np.sum(x, axis=0))  # Сумма элементов в каждом столбце; "[5 7 9]"
print(np.sum(x, axis=1))  # Сумма элементов в каждой строчке; "[6 15]"

print(np.max(x, axis=1))  # Максимум в каждой строчке; "[3 6]" 

21
[5 7 9]
[ 6 15]
[3 6]


Как мы можем вычислить индекс максимального значения каждой строки? Напрмер, найти класс, который соответствует максимальной вероятности для входного изображения.

In [26]:
x = np.array([[0.1, 0.4, 0.5], 
              [0.2, 0.5, 0.6]])

print(np.argmax(x, axis=1)) # Индекс максимума в каждой строчке; "[2 2]"

[2 2]


Мы можем найти индексы элементов, удовлетворяющих некоторым условиям, используя `np.where`

In [27]:
print(np.where(nums > 5))
print(nums[np.where(nums > 5)])

(array([6, 7], dtype=int64),)
[6 7]


Обратите внимание, что ось, к которой вы применяете операцию, будет схлопнута.
Это полезно иметь в виду, когда вы пытаетесь выяснить соответствие осей.

In [28]:
x = np.array([[1, 2, 3], 
              [4, 5, 6]])

print('x ndim:', x.ndim)
print((x.max(axis=0)).ndim) # Взятие максимума по оси 0 имеет размер (3,)
                            # соответствуя 3 столбцам.

# Трёхмерный массив (массив ранга 3)
x = np.array([[[1, 2, 3], 
               [4, 5, 6]],
              [[10, 23, 33], 
               [43, 52, 16]]
             ])

print('x ndim:', x.ndim)          # Имеет размер (2, 2, 3)
print((x.max(axis=1)).ndim)       # Взятие максимума по оси 1 имеет размер (2, 3)
print((x.max(axis=(1, 2))).ndim)  # Может взять максимум по нескольким осям; [6 52]

x ndim: 2
1
x ndim: 3
2
1


## Индексирование

NumPy также предоставляет мощные схемы индексирования.

In [29]:
# Создаёт следующий массив ранга 2 размера (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])
print('Original:\n', a)

# Можно выбрать элемент, как в 2-мерном списке Python
print('Element (0, 0) (a[0][0]):\n', a[0][0])   # Prints 1
# или следующим образом
print('Element (0, 0) (a[0, 0]) :\n', a[0, 0])  # Prints 1

# Используя слайсинг, можно вытащить подмассив, состоящий из первых двух строк
# и столбцов 1 и 2; получившийся массив имеет размерность (2, 2):
# [[2 3]
#  [6 7]]
print('Sliced (a[:2, 1:3]):\n', a[:2, 1:3])

# Шаги также поддерживаются в индексации. Следующий пример разворачивает первый ряд:
print('Reversing the first row (a[0, ::-1]) :\n', a[0, ::-1]) # [4 3 2 1]

# Слайс по первой размерности, работает для n-мерных массивов, где n >= 1
print('slice the first row by the [...] operator: \n', a[0, ...])

Original:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Element (0, 0) (a[0][0]):
 1
Element (0, 0) (a[0, 0]) :
 1
Sliced (a[:2, 1:3]):
 [[2 3]
 [6 7]]
Reversing the first row (a[0, ::-1]) :
 [4 3 2 1]
slice the first row by the [...] operator: 
 [1 2 3 4]


Часто бывает полезно выбрать или изменить один элемент из каждой строки матрицы. В следующем примере используется **fancy indexing**, где мы индексируем массив, используя массив индексов (скажем, массив целых чисел или булевых значений):

In [30]:
# Создаём новый массив, из которого мы будем выбирать элементы
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [10, 11, 12]])

print(a)  # "array([[ 1,  2,  3],
          #         [ 4,  5,  6],
          #         [ 7,  8,  9],
          #         [10, 11, 12]])"

# Создаём массив индексов
b = np.array([0, 2, 0, 1])

# Выбераем один элемент из каждой строки a, используя индексы в b
print(a[np.arange(4), b])  # "[ 1  6  7 11]"

# то же, что и
for x, y in zip(np.arange(4), b):
    print(a[x, y])

c = a[0]
c[0] = 100
print(a)

# Изменять по одному элементу из каждой строки a, используя индексы из b
a[np.arange(4), b] += 10

print(a)  # "array([[11,  2,  3],
          #        [ 4,  5, 16],
          #        [17,  8,  9],
          #        [10, 21, 12]])


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  6  7 11]
1
6
7
11
[[100   2   3]
 [  4   5   6]
 [  7   8   9]
 [ 10  11  12]]
[[110   2   3]
 [  4   5  16]
 [ 17   8   9]
 [ 10  21  12]]


Мы также можем использовать логическое индексирование/маски. Предположим, мы хотим установить все элементы больше, чем MAX, равными MAX:

In [31]:
MAX = 5
nums = np.array([1, 4, 10, -1, 15, 0, 5])
print(nums > MAX)            # [False, False, True, False, True, False, False]

nums[nums > MAX] = 100
print(nums)                  # [1, 4, 5, -1, 5, 0, 5]

[False False  True False  True False False]
[  1   4 100  -1 100   0   5]


In [32]:
nums = np.array([1, 4, 10, -1, 15, 0, 5])
nums > 5

array([False, False,  True, False,  True, False, False])

Обратите внимание, что индексы в fancy indexing могут появляться в любом порядке и даже несколько раз:

In [33]:
nums = np.array([1, 4, 10, -1, 15, 0, 5])
print(nums[[1, 2, 3, 1, 0]])  # Prints [4 10 -1 4 1]

[ 4 10 -1  4  1]


## Broadcasting (Трансляция)

Многие из операций, которые мы рассмотрели выше, включали массивы одинакового ранга. 
Однако часто мы можем иметь меньший массив и использовать его несколько раз для обновления массива больших размерностей. 
Например, рассмотрим приведенный ниже пример смещения среднего значения каждого столбца от элементов соответствующего столбца:

In [34]:
x = np.array([[1, 2, 3],
              [3, 5, 7]])
print(x.shape)  # (2, 3)

col_means = x.mean(axis=0)
print(col_means)          # [2. 3.5 5.]
print(col_means.shape)    # (3,)
                          # Имеет меньший ранг, чем x!

mean_shifted = x - col_means
print('\n', mean_shifted)
print(mean_shifted.shape)  # (2, 3)

(2, 3)
[2.  3.5 5. ]
(3,)

 [[-1.  -1.5 -2. ]
 [ 1.   1.5  2. ]]
(2, 3)


Или даже просто умножить матрицу на 2:

In [35]:
x = np.array([[1, 2, 3],
              [3, 5, 7]])
print(x * 2) # [[ 2  4  6]
             #  [ 6 10 14]]


[[ 2  4  6]
 [ 6 10 14]]


Broadcasting (Трансляция) двух массивов следует этим правилам:

1. Если массивы имеют разные ранги, добавьте к массиву более низкого ранга размерность слева (аналогично оборачиванию списка в список), пока оба массива не будут иметь одинаковый ранг.
2. Два массива считаются совместимыми в измерении, если они имеют одинаковый размер в измерении, или если один из массивов имеет размер 1 в этом измерении.
3. Массивы могут транслироваться вместе, если они совместимы во всех измерениях.
4. После трансляции каждый массив ведет себя так, как если бы он имел форму, равную элементному максимуму форм двух входных массивов.
5. В любом измерении, где один массив имеет размер 1, а другой - больше 1, первый массив ведет себя так, как если бы он был скопирован вдоль этого измерения.

Например, при вычитании столбцов выше, мы имели массивы формы (2, 3) и (3,).

1. Эти массивы не имеют одинакового ранга, поэтому мы добавим измерение к массиву более низкого ранга, чтобы сделать его (1, 3).
2. (2, 3) и (1, 3) совместимы (имеют одинаковый размер в измерении, или если один из массивов имеет размер 1 в этом измерении).
3. Можно транслировать вместе!
4. После трансляции каждый массив ведет себя так, как если бы он имел форму, равную (2, 3).
5. Меньший массив будет вести себя так, как если бы он был скопирован вдоль измерения 0.

Давайте попробуем вычесть среднее значение каждой строки!

In [36]:
x = np.array([[1, 2, 3],
              [3, 5, 7]])

row_means = x.mean(axis=1)
print(row_means)  # [2. 5.]

mean_shifted = x - row_means

[2. 5.]


ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

Чтобы выяснить, что не так, выведем размерности:

In [37]:
x = np.array([[1, 2, 3],
              [3, 5, 7]])
print(x.shape)  # Prints (2, 3)

row_means = x.mean(axis=1)
print(row_means)        # Prints [2. 5.]
print(row_means.shape)  # Prints (2,)

(2, 3)
[2. 5.]
(2,)


Что произошло?

Ответ: если бы мы следовали правилу трансляции 1, то мы бы добавили 1 к меньшему ранговому массиву чтобы получить (1, 2). Однако последние измерения теперь не совпадают между (2, 3) и (1, 2), и поэтому мы не можем транслировать.

Явно добавив размерность в нужном направлении (справа), мы получим желаемое поведение:

In [38]:
x = np.array([[1, 2, 3],
              [3, 5, 7]])
print(x.shape)  # Prints (2, 3)

row_means = x.mean(axis=1)
print('row_means shape:', row_means.shape)
print('expanded row_means shape: ', np.expand_dims(row_means, axis=1).shape)

mean_shifted = x - np.expand_dims(row_means, axis=1)
print(mean_shifted)
print(mean_shifted.shape)  # Prints (2, 3)

(2, 3)
row_means shape: (2,)
expanded row_means shape:  (2, 1)
[[-1.  0.  1.]
 [-2.  0.  2.]]
(2, 3)


Больше примеров трансляции!

In [39]:
# Посчитать внешнее произведение векторов
v = np.array([1, 2, 3])  # v имеет размер (3,)
w = np.array([4, 5])    # w имеет размер (2,)
# Чтобы вычислить внешнее произведение, мы сначала преобразуем v в вектор-столбец
# размера (3, 1); затем мы можем транслировать его против w, чтобы получить 
# матрицу формы (3, 2), которая является внешним произведением v и w:
# [[ 4  5]
#  [ 8 10]
#  [12 15]]
print(np.reshape(v, (3, 1)) * w)

# Добавим вектор к каждой строке матрицы
x = np.array([[1, 2, 3], [4, 5, 6]])
# x имеет форму (2, 3), а v - форму (3,), поэтому они транслируются в (2, 3), 
# возвращая следующую матрицу:
# [[2 4 6]
#  [5 7 9]]
print(x + v)

# Добавьте вектор к каждому столбцу матрицы
# x имеет форму (2, 3), а w - форму (2,).
# Если мы транспонируем x, то он будет иметь форму (3, 2) и может транслироваться
# к w, чтобы получить результат формы (3, 2); транспонирование этого результата
# дает конечный результат формы (2, 3), который является матрицей x с
# вектор w добавленным к каждому столбцу. Получается следующая матрица:
# [[ 5  6  7]
#  [ 9 10 11]]
print((x.T + w).T)
# Другое решение состоит в том, чтобы преобразовать w в вектор-столбец (2, 1);
# затем мы можем транслировать его непосредственно к x, чтобы получить тот же результат.
print(x + np.reshape(w, (2, 1)))

[[ 4  5]
 [ 8 10]
 [12 15]]
[[2 4 6]
 [5 7 9]]
[[ 5  6  7]
 [ 9 10 11]]
[[ 5  6  7]
 [ 9 10 11]]


## Представление (Views) vs. Копия (Copies)

В отличии от copy, в **представлении** массива, данные совместно используются между представлением и массивом. Иногда результаты являются копиями массивов, но в других случаях они могут быть представлениями. Понимание того, когда что генерируется важно, чтобы избежать каких-либо непредвиденных проблем.

Представления можно создавать из среза массива, изменяя dtype той же области данных (с помощью arr.view(dtype), а не результат arr.astype(dtype)).

In [40]:
x = np.arange(5)
print('Original:\n', x)  # [0 1 2 3 4]

# Изменение представления приведет к изменению массива
view = x[1:3]
view[1] = -1
print('Array After Modified View:\n', x)  # [0 1 -1 3 4]

Original:
 [0 1 2 3 4]
Array After Modified View:
 [ 0  1 -1  3  4]


In [41]:
x = np.arange(5)
view = x[1:3]
view[1] = -1

# Изменение массива приведет к изменению представления
print('View Before Array Modification:\n', view)  # [1 -1]
x[2] = 10
print('Array After Modifications:\n', x)          # [0 1 10 3 4]
print('View After Array Modification:\n', view)   # [1 10]

View Before Array Modification:
 [ 1 -1]
Array After Modifications:
 [ 0  1 10  3  4]
View After Array Modification:
 [ 1 10]


However, if we use fancy indexing, the result will actually be a copy and not a view:

In [42]:
x = np.arange(5)
print('Original:\n', x)  # Prints [0 1 2 3 4]

# Изменение результата выбора из-за fancy indexing
# не будет изменять исходный массив.
copy = x[[1, 2]]
copy[1] = -1
print('Copy:\n', copy) # [1 -1]
print('Array After Modified Copy:\n', x)  # [0 1 2 3 4]

Original:
 [0 1 2 3 4]
Copy:
 [ 1 -1]
Array After Modified Copy:
 [0 1 2 3 4]


In [43]:
# Еще один пример, связанный с fancy indexing
x = np.arange(5)
print('Original:\n', x)  # [0 1 2 3 4]

copy = x[x >= 2]
print('Copy:\n', copy) # [2 3 4]
x[3] = 10
print('Modified Array:\n', x)  # [0 1 2 10 4]
print('Copy After Modified Array:\n', copy)  # [2 3 4]

Original:
 [0 1 2 3 4]
Copy:
 [2 3 4]
Modified Array:
 [ 0  1  2 10  4]
Copy After Modified Array:
 [2 3 4]


## Summary

1. NumPy - это невероятно мощная библиотека для вычислений, обеспечивающая как огромный прирост эффективности, так и удобство.
2. Векторизация! На порядки быстрее.
3. Отслеживание формы ваших массивов зачастую полезно.
4. Множество полезных математические функций и операций, встроенных в NumPy.
5. Выбор и манипулирование произвольными фрагментами данных с помощью мощных схем индексирования.
6. Трансляция позволяет производить вычисления в массивах различной формы.
7. Следите за представлениями и копиями.